[WIP]  spec/system をSelenium経由で実行する
next-l/enju_leaf pull request #1804
Opened 2023-06-28 06:39 UTC by kimihito

**作業中です**

ref #1374

2023-07-10 12:22 UTC, kimihito commented
>　* [ ] Seleniumは本番環境では使用しないので、 docker-compose.yml とは別で実行する

Dockerの知識が不足しているせいか、時間がかかりそうなので一旦こちらの対応はスキップしたいと思います。

2023-07-10 12:36 UTC, kimihito reviewed
変更に関する補足をコメントしています。

2023-07-10 12:36 UTC, kimihito commented on Gemfile
> -  gem 'webdrivers'
Railsが動く環境にSystem Spec用のブラウザをインストールする場合は必要だが、今回ブラウザの環境（≒ Selenium）はRailsとは別のコンテナで使用しているために削除しました

2023-07-10 12:36 UTC, kimihito commented on docker-compose.yml
> +    # - selenium
Seleniumを動作するためにはコメントアウトが必要です

2023-07-10 12:36 UTC, kimihito commented on docker-compose.yml
> +      # - SELENIUM_DRIVER_URL=http://selenium:4444/wd/hub
Seleniumを動作するためにはコメントアウトが必要です

2023-07-10 12:36 UTC, kimihito commented on docker-compose.yml
> +  #   shm_size: 2gb
Seleniumを動作するためにはコメントアウトが必要です

2023-07-10 12:36 UTC, kimihito commented on spec/rails_helper.rb
> -  end
今回ブラウザの環境（≒ Selenium）はRailsとは別のコンテナで使用しているために削除しました

2023-07-10 12:36 UTC, kimihito commented on spec/support/precompile_assets.rb
> +  config.before(:suite) do
JavaScriptでの動作も確認したいため、 `assets:precompile` を実行しています。これはSystem Specを実行するテストの前に1回だけ実行されます（≒  2つsystem specがあっても、1度だけ `assets:precompile` が実行されます）

2023-07-10 12:37 UTC, kimihito commented
@nabeta お手すきの際にレビューの方をお願いします 🙏

2023-08-15 08:52 UTC, nabeta requested changes

2023-08-15 08:52 UTC, nabeta commented on docker-compose.yml
> +    # - selenium
@kimihito 遅くなってすみません。コメントのみを追加部分している部分は、削除できますでしょうか。

2023-08-19 04:37 UTC, nabeta commented
@kimihito https://github.com/next-l/enju_leaf/pull/1813 で、他のテストをコンテナ内で実行できるようにしており、そちらをこのPRに反映させたのですが、"Precompiling assets."というメッセージが出て終了してしまいます。

```sh
$ docker compose run --rm web rspec spec/system
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "RAILS_ENV" variable is not set. Defaulting to a blank string. 
WARN[0000] The "RAILS_ENV" variable is not set. Defaulting to a blank string. 
WARN[0000] The "CANTALOUPE_BASE_URI" variable is not set. Defaulting to a blank string. 
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "RAILS_ENV" variable is not set. Defaulting to a blank string. 
WARN[0000] The "RAILS_ENV" variable is not set. Defaulting to a blank string. 
WARN[0000] The "CANTALOUPE_BASE_URI" variable is not set. Defaulting to a blank string. 
[+] Creating 3/0
 ✔ Container enju_leaf-solr-1      Running                                 0.0s 
 ✔ Container enju_leaf-redis-1     Runnin...                               0.0s 
 ✔ Container enju_leaf-selenium-1  Run...                                  0.0s 

 Precompiling assets.
```

`spec/support/precompile_assets.rb`を削除すると、テストが実行されます。なにか状況がわかりますでしょうか。

```
$ rm spec/support/precompile_assets.rb
$ docker compose run --rm web rspec spec/system
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "RAILS_ENV" variable is not set. Defaulting to a blank string. 
WARN[0000] The "RAILS_ENV" variable is not set. Defaulting to a blank string. 
WARN[0000] The "CANTALOUPE_BASE_URI" variable is not set. Defaulting to a blank string. 
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "RAILS_ENV" variable is not set. Defaulting to a blank string. 
WARN[0000] The "RAILS_ENV" variable is not set. Defaulting to a blank string. 
WARN[0000] The "CANTALOUPE_BASE_URI" variable is not set. Defaulting to a blank string. 
[+] Creating 3/0
 ✔ Container enju_leaf-solr-1      Running                                 0.0s 
 ✔ Container enju_leaf-redis-1     Runnin...                               0.0s 
 ✔ Container enju_leaf-selenium-1  Run...                                  0.0s 
.......................**......................

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Libraries When logged in as Administrator should show library config
     # Temporarily skipped with xit
     # ./spec/system/libraries_spec.rb:12

  2) Libraries When logged in as Librarian should not show library config
     # Temporarily skipped with xit
     # ./spec/system/libraries_spec.rb:23


Finished in 32.8 seconds (files took 2.92 seconds to load)
47 examples, 0 failures, 2 pending

Coverage report generated for RSpec to /enju/coverage. 3481 / 16741 LOC (20.79%) covered.
```

2023-08-19 04:39 UTC, nabeta commented
@kimihito なお、上記はdocker-compose.ymlを以下のように変更して実行しています。

```diff
$ git diff docker-compose.yml
diff --git a/docker-compose.yml b/docker-compose.yml
index 131d2b294..1c3611d7e 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -28,7 +28,7 @@ x-app: &app
   depends_on:
     - solr
     - redis
-    # - selenium
+    - selenium
   restart: always
 
 services:
@@ -37,7 +37,7 @@ services:
     command: bash -c "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0"
     environment:
       - WEBPACKER_DEV_SERVER_HOST=webpacker
-      # - SELENIUM_DRIVER_URL=http://selenium:4444/wd/hub
+      - SELENIUM_DRIVER_URL=http://selenium:4444/wd/hub
     expose:
       - 3000
 
@@ -126,10 +126,12 @@ services:
     networks:
       internal:
 
-  # selenium:
-  #   image: selenium/standalone-chrome:114.0
-  #   ports:
-  #     - 4444:4444
-  #     - 7900:7900
-  #     - 5900:5900
-  #   shm_size: 2gb
+  selenium:
+    image: selenium/standalone-chrome:114.0
+    networks:
+      internal:
+    ports:
+      - 4444:4444
+      - 7900:7900
+      - 5900:5900
+    shm_size: 2gb
```

2023-08-19 22:25 UTC, kimihito commented
> @kimihito https://github.com/next-l/enju_leaf/pull/1813 で、他のテストをコンテナ内で実行できるようにしており、そちらをこのPRに反映させたのですが、"Precompiling assets."というメッセージが出て終了してしまいます。
> 

> 
> `spec/support/precompile_assets.rb`を削除すると、テストが実行されます。なにか状況がわかりますでしょうか。
> 

動作チェックありがとうございます。手元でも確認したいので少しお時間ください。

なお `spec/support/precompile_assets.rb`ではJavaScriptやCSSの利用をテストで出来るようにするためのものです。こちら削除して実行したテストはCSSやJavaScriptが反映されていないものになるかと思います。 save_screenshot などのメソッドで画面のスクリーンショットを撮影すると画面がわかるので、そちらでCSSが反映されているかご確認いただけますか？ @nabeta

2023-08-21 16:48 UTC, nabeta commented
@kimihito もともとの環境では https://github.com/next-l/enju_leaf/commit/616d6aeeab12e496796a615cb1fc9901a186fc97 を反映した状態でも状況は変わらなかったのですが、新しくcloneし直してテストを実行したところ、正常に`rake assets:precompile`が実行された後にテストが走るようになりました。なにか余分なファイルがあったのかもしれません。

docker-compose.ymlをテストのときにのみ実行するように変更して、マージしたいと思います。

2023-08-22 14:10 UTC, nabeta commented
Seleniumのコンテナの設定を`docker-compose.test.yml`に移動しました。以下のようにファイルを明示的に指定して実行するか、

```sh
docker compose -f docker-compose.yml -f docker-compose.test.yml run --rm web rspec spec/system
```

docker-compose.override.ymlにコピーして実行します。

```sh
cp docker-compose.test.yml docker-compose.override.yml
docker compose run --rm web rspec spec/system
```

2023-08-22 14:37 UTC, merged

2023-08-23 00:54 UTC, kimihito commented
ご対応ありがとうございました 🙏